CREATE TABLE CUSTOMERS
(
ID INT,
NAME VARCHAR(30),
AGE VARCHAR(30),
ADDRESS VARCHAR(30),
SALARY VARCHAR(30)
)

INSERT INTO CUSTOMERS VALUES('1', 'RAMESH', '32', 'AHMEDABAD', '2000')

INSERT INTO CUSTOMERS VALUES('8', 'RAMESH', '32', 'AHMEDABAD', '4000')

INSERT INTO CUSTOMERS VALUES('2', 'SANJEET', '25', 'DELHI', '6000')

INSERT INTO CUSTOMERS VALUES('3', 'RANJEET', '23', 'KOTA', '15000')

INSERT INTO CUSTOMERS VALUES('4', 'RAKESH', '25', 'MUMBAI', '8000')

INSERT INTO CUSTOMERS VALUES('5', 'ANUJ', '27', 'BHOPAL', '12000')
INSERT INTO CUSTOMERS VALUES('6', 'ANISH', '22', 'MP', '15000')
INSERT INTO CUSTOMERS VALUES('7', 'VIVEK', '24', 'INDORE', '18000')

SELECT * FROM CUSTOMERS;

SELECT * FROM CUSTOMERS WHERE AGE >= 25 AND SALARY >= 6500;

SELECT * FROM CUSTOMERS WHERE AGE >= 25 OR SALARY >= 6500;

SELECT * FROM CUSTOMERS WHERE AGE IS NOT NULL;

SELECT * FROM CUSTOMERS WHERE NAME LIKE 'SA%';

SELECT * FROM CUSTOMERS WHERE AGE IN ( 25, 27 );

SELECT * FROM CUSTOMERS WHERE AGE BETWEEN 25 AND 27;

SELECT AGE FROM CUSTOMERS 
WHERE EXISTS (SELECT AGE FROM CUSTOMERS WHERE SALARY > 6500);

SELECT * FROM CUSTOMERS 
WHERE AGE > ALL (SELECT AGE FROM CUSTOMERS WHERE SALARY > 6500);

SELECT * FROM CUSTOMERS 
WHERE AGE > ANY (SELECT AGE FROM CUSTOMERS WHERE SALARY > 6500);